# SPDX-License-Identifier: AGPL-3.0-only
"""core baseline — songs, jobs, lyrics_sets

The shape every DEPLOYED database is already in. Existing installs (including
the live one) are detected by ``db.bootstrap.ensure_schema``, verified against
this shape, and STAMPED at this revision — they never execute the statements
below. Only fresh installs run them.

Generated with ``alembic revision --autogenerate`` from the ORM rather than
hand-written, so the baseline cannot drift from the models;
``test_fresh_upgrade_matches_metadata`` keeps it that way forever.

``owner_id`` is present as a **nullable, FK-less** integer. That is deliberate
(user ruling "Option A", 2026-07-23): core single-host scoping keys off
``owner_id == SINGLE_HOST_ID`` through the same query path premium uses for
tenant isolation, so the column is core plumbing, not a premium column. There
is no FK to ``users`` and no premium table here — the public revision graph
stays premium-free. Existing DBs keep whatever FK/NOT NULL they were built
with (they are stamped, not rebuilt); premium re-adds DB-level enforcement in
its own chain.

``queue_entries`` is deliberately NOT in this baseline — it is net-new and
lives in c0002, because a stamped DB would otherwise never create it.

Revision ID: c0001
Revises:
Create Date: 2026-07-26

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('stems_path', sa.String(length=512), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('active_lyrics_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('word_sync_json', sa.Text(), nullable=True),
    sa.Column('custom_lyrics', sa.Text(), nullable=True),
    sa.Column('lyrics_synced', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['active_lyrics_id'], ['lyrics_sets.id'], name='fk_songs_active_lyrics', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_songs_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_title'), ['title'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('stems', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_song_id'), ['song_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('lyrics_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('plain_lyrics', sa.Text(), nullable=True),
    sa.Column('synced_lyrics', sa.Text(), nullable=True),
    sa.Column('word_sync_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', 'id', name='uq_lyrics_song_id')
    )
    with op.batch_alter_table('lyrics_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lyrics_sets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lyrics_sets_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_lyrics_sets_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lyrics_sets_song_id'), ['song_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lyrics_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lyrics_sets_song_id'))
        batch_op.drop_index(batch_op.f('ix_lyrics_sets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_lyrics_sets_is_verified'))
        batch_op.drop_index(batch_op.f('ix_lyrics_sets_id'))

    op.drop_table('lyrics_sets')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_song_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_owner_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_songs_title'))
        batch_op.drop_index(batch_op.f('ix_songs_status'))
        batch_op.drop_index(batch_op.f('ix_songs_owner_id'))
        batch_op.drop_index(batch_op.f('ix_songs_job_id'))
        batch_op.drop_index(batch_op.f('ix_songs_id'))
        batch_op.drop_index(batch_op.f('ix_songs_artist'))

    op.drop_table('songs')
    # ### end Alembic commands ###
